version: 0.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
skip_commits:
   files:
    - docs/*
    - '**/*.html'
    - '**/*.md'
    - appveyor.yml
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 7/Amy0vozNWOuINB5sIjU3ChZc16Oye9bcOeCfuSpy1sYN0j4XhQ1EKS5+UDsANS
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: I0crkaDLJwNba1txPPCrj0pKaFMbzxKHPIZ7hNYP1Wy6yVJ7s3napz/nEv38L/3/
  on:
    branch: master
