skip_non_tags: true
image: Visual Studio 2017
configuration: Release
skip_commits:
   files:
    - docs/*
    - '**/*.html'
    - '**/*.md'
    - appveyor.yml
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 7/Amy0vozNWOuINB5sIjU3ChZc16Oye9bcOeCfuSpy1sYN0j4XhQ1EKS5+UDsANS
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: I0crkaDLJwNba1txPPCrj0pKaFMbzxKHPIZ7hNYP1Wy6yVJ7s3napz/nEv38L/3/
  on:
    branch: master
install:
  - choco install gitversion.portable -pre -y

assembly_info:
   patch: true
   file: '**\AssemblyInfo.*'
   assembly_version: $(GitVersion_AssemblySemVer)
   assembly_file_version: $(GitVersion_AssemblySemVer)
   assembly_informational_version: $(GitVersion_FullSemVer)


before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver

on_failure:
  - ps: 7z a "WorkingTree.zip"
  - ps: Push-AppveyorArtifact WorkingTree.zip